# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='chat/static/pp/pp.jpeg', upload_to='user_img'),
        ),
    ]
